## Either you define a specific port or you can use this format '${PORT:${SERVER_PORT:0}}'
server:
  port: 9081

spring:
  application:
    name: feign-client-1
    
## Here, the location to Eureka Server is directly configured in the application itself
eureka:
  client:
    serviceUrl:
       defaultZone: http://eureka:8010/eureka/
      
