package jaraws.hibernate.model;

import java.util.ArrayList;
import java.util.Collection;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Table;

import org.hibernate.annotations.CollectionId;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

/**
 * Defining this Student class as an Entity class i.e a separate table in the
 * database will be created by Hibernate in database for this entity.
 * 
 * @author Swaraj
 *
 */
@Entity
@Table(name = "STUDENT")
public class Student {

	/*
	 * These are following steps carries out by hibernate while managing the Id
	 * generation by itself.
	 * 
	 * 1. drop table if exists hibernate_sequence 2. create table hibernate_sequence
	 * (next_val bigint); 3. select next_val as swaraj from hibernate_sequence for
	 * update; 4. update hibernate_sequence set next_val= 3 where next_val=2;
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "STUDENT_ID")
	private int id;
	@Column(name = "FIRST_NAME")
	private String firstName;
	@Column(name = "LAST_NAME")
	private String lastName;
	@Column(name = "AGE")
	private int age;

	/*
	 * In order to have a primary key column we need to have a collection that supports
	 * index. And for the same we will change the collection here from Set to ArrayList.
	 * 
	 * Apart from that we have used an HIBERNATE annotation @ColledtionId here to define
	 * the identifier for this collection. The identifier here is named as ADDRESS_ID
	 * which of of type long and will be generated by HILO generator of Hibernate.
	 * 
	 * Using this @CollectionId annotation here will bound our application with Hibernate
	 * as JPA implementation.
	 */
	@ElementCollection
	//@CollectionTable(name = "student_addresses", joinColumns = @JoinColumn(name = "id"))
	@JoinTable(name="STUDENT_ADDRESS",
		joinColumns=@JoinColumn(name="STUDENT_ID") // The join column which will be used by @JoinTable table will be created by name 'STUDENT_ID'
	)
	@GenericGenerator(name = "HILO-GEN", strategy = "increment")
	@CollectionId(columns = { @Column(name="ADDRESS_ID") }, generator = "HILO-GEN", type = @Type(type="long"))
	private Collection<Address> listOfAddresses = new ArrayList<Address>();

	public Student() {

	}

	public int getId() {
		return id;
	}	

	public void setId(int id) {
		this.id = id;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	

	public Collection<Address> getListOfAddresses() {
		return listOfAddresses;
	}

	public void setListOfAddresses(Collection<Address> listOfAddresses) {
		this.listOfAddresses = listOfAddresses;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Student [id=");
		builder.append(id);
		builder.append(", firstName=");
		builder.append(firstName);
		builder.append(", lastName=");
		builder.append(lastName);
		builder.append(", age=");
		builder.append(age);
		builder.append(", listOfAddresses=");
		builder.append(listOfAddresses);
		builder.append("]");
		return builder.toString();
	}
}
